# Port of API Gateway
http:
  port: 8080
# Admin interface
admin:
  port: 9876
  host: localhost
apiEndpoints:
  users:
    paths:
      - '/users'
      - '/users/*'
  questions:
    paths:
      - '/questions'
      - '/questions/*'
  matchings:
    paths:
      - '/matchings'
      - '/matchings/*'
serviceEndpoints:
  # Used in the format of ${ENV_VARIABLE_NAME:-DEFAULT_VALUE}
  user-service:
    url: ${USER_SERVICE_URL:-'http://localhost:8000'}
  question-service:
    url: ${QUESTION_SERVICE_URL:-'http://localhost:8001'}
  matching-service:
    url: ${MATCHING_SERVICE_URL:-'http://localhost:8002'}
policies:
  - cors
  - expression
  - log
  - proxy
pipelines:
  users:
    apiEndpoints:
      - users
    policies:
      - proxy:
          - action:
              serviceEndpoint: user-service
              changeOrigin: true
  questions:
    apiEndpoints:
      - questions
    policies:
      - proxy:
          - action:
              serviceEndpoint: question-service
              changeOrigin: true
  matchings:
    apiEndpoints:
      - matchings
    policies:
      - proxy:
          - action:
              serviceEndpoint: matching-service
              changeOrigin: true
