apiVersion: v1
data:
  DB_CLOUD_URI: <CONNECTION_STRING>
  DB_LOCAL_URI: mongodb://admin:password@mongodb:27017/peerprep-g02?authSource=admin
  DEAD_LETTER_QUEUE_TIMEOUT: "10"
  ENV: LOCAL
  JWT_SECRET: you-can-replace-this-with-your-own-secret
  PORT: "8002"
  QUESTION_SVC_GATEWAY_URL: http://nginx-gateway:8080/questions
  QUEUE_TIMEOUT: "20"
  RABBITMQ_LOCAL_URI: amqp://admin:password@rabbitmq:5672
  REDIS_LOCAL_URL: redis://redis:6379
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: matching-service-matching-service-docker-env
  name: matching-service-docker-env
