apiVersion: v1
data:
  mongod.conf: |
    systemLog:
      destination: file
      path: /var/log/mongodb/mongod.log
      verbosity: 1
      quiet: true
      component:
        network:
          verbosity: 0
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: mongodb
  name: mongodb-cm1
