apiVersion: v1
data:
  COLLAB_SERVICE_URL: collab-service:8003
  MATCHING_SERVICE_URL: matching-service:8002
  QUESTION_SERVICE_URL: question-service:8001
  USER_SERVICE_URL: user-service:8000
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: nginx-gateway-nginx-gateway-env
  name: nginx-gateway-env
