services:
  api-gateway:
    # Automatically build the image with latest tag
    build: ./..
    image: api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    env_file:
      - ./../.docker.env
    networks:
      - shared-network

networks:
  shared-network:
    name: peerprep-g02
