services:
  nginx:
    build: ./..
    image: nginx
    container_name: nginx
    ports:
      - "8080:8080"
    env_file:
      - ./../.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - shared-network

networks:
  shared-network:
    name: peerprep-g02
