services:
  frontend:
    # Automatically build the image with latest tag
    build: ./..
    image: frontend
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - ./../.docker.env
    networks:
      - shared-network

networks:
  shared-network:
    name: peerprep-g02
