services:
  frontend:
    # Automatically build the image with latest tag
    build: ./..
    image: frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      # Enable hot reload by mounting these folders.
      # Any changes locally should reload the react app in the container
      - ./../src:/app/src
      - ./../public:/app/public
      - ./../config:/app/config
    env_file:
      - ./../.docker.env
    networks:
      - shared-network

networks:
  shared-network:
    name: peerprep-g02
