name: Run Frontend Tests in Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx (optional but good for caching)
        uses: docker/setup-buildx-action@v2

      - name: Run frontend tests via Docker Compose
        run: |
          docker-compose -f .ci/frontend-test/provisioning/docker-compose.yml \
            up --build --abort-on-container-exit --exit-code-from frontend-test