services:
  user-service:
    # Automatically build the image with latest tag
    build: ./..
    image: user-service
    container_name: user-service
    ports:
      - "8000:8000"
    volumes:
      - ./../controller:/app/controller       
      - ./../routes:/app/routes                
      - ./../model:/app/model                  
      - ./../middleware:/app/middleware       
      - ./../index.js:/app/index.js            
      - ./../server.js:/app/server.js          
    
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./../.docker.env
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:8000/health" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - shared-network

networks:
  shared-network:
    name: peerprep-g02
