services:
  mongodb:
    extends:
      file: db/docker-compose.yml
      service: mongodb

  mongo-express:
    extends:
      file: db/docker-compose.yml
      service: mongo-express
    depends_on:
      - mongodb

  rabbitmq:
    extends:
      file: db/docker-compose.yml
      service: rabbitmq

  api-gateway:
    extends:
      file: ./../api-gateway/provisioning/docker-compose.yml
      service: api-gateway

  user-service:
    extends:
      file: ./../user-service/provisioning/docker-compose.yml
      service: user-service
    depends_on:
      - mongodb

  question-service:
    extends:
      file: ./../question-service/provisioning/docker-compose.yml
      service: question-service
    depends_on:
      - mongodb

# TODO: Need a better way to do depends on.
#  matching-service:
#    extends:
#      file: ./../matching-service/provisioning/docker-compose.yml
#      service: matching-service
#    depends_on:
#      - rabbitmq
#      - mongodb
#      - question-service
#      - api-gateway

  frontend:
    extends:
      file: ./../frontend/provisioning/docker-compose.yml
      service: frontend
    depends_on:
      - mongodb
      - question-service
      - user-service
      - rabbitmq

networks:
  shared-network:
    name: peerprep-g02
