services:
  mongodb:
    extends:
      file: db/docker-compose.yml
      service: mongodb

  mongo-express:
    extends:
      file: db/docker-compose.yml
      service: mongo-express
    depends_on:
      mongodb:
        condition: service_healthy

  rabbitmq:
    extends:
      file: db/docker-compose.yml
      service: rabbitmq

  api-gateway:
    extends:
      file: ./../api-gateway/provisioning/docker-compose.yml
      service: api-gateway

  user-service:
    extends:
      file: ./../user-service/provisioning/docker-compose.yml
      service: user-service
    depends_on:
      mongodb:
        condition: service_healthy

  question-service:
    extends:
      file: ./../question-service/provisioning/docker-compose.yml
      service: question-service
    depends_on:
      mongodb:
        condition: service_healthy

  matching-service:
    extends:
      file: ./../matching-service/provisioning/docker-compose.yml
      service: matching-service
    depends_on:
      rabbitmq:
        condition: service_healthy
      api-gateway:
        condition: service_healthy
      question-service:
        condition: service_healthy

  frontend:
    extends:
      file: ./../frontend/provisioning/docker-compose.yml
      service: frontend
    depends_on:
      mongodb:
        condition: service_healthy
      api-gateway:
        condition: service_healthy
      question-service:
        condition: service_healthy
      user-service:
        condition: service_healthy
      matching-service:
        condition: service_healthy


networks:
  shared-network:
    name: peerprep-g02
