services:
  question-service:
    # Automatically build the image with latest tag
    build: ./..
    image: question-service
    container_name: question-service
    ports:
      - "8001:8001"
    env_file:
      - ./../.docker.env
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:8001/health" ]
      interval: 3s
      timeout: 5s
      retries: 3
    networks:
      - shared-network

networks:
  shared-network:
    name: peerprep-g02
