# Use this docker compose if running cloud db
services:
  rabbitmq:
    extends:
      file: ./../db/docker-compose.yml
      service: rabbitmq

  nginx:
    extends:
      file: ./../../nginx/provisioning/docker-compose.yml
      service: nginx

  user-service:
    extends:
      file: ./../../user-service/provisioning/docker-compose.yml
      service: user-service

  question-service:
    extends:
      file: ./../../question-service/provisioning/docker-compose.yml
      service: question-service

  matching-service:
    extends:
      file: ./../../matching-service/provisioning/docker-compose.yml
      service: matching-service
    depends_on:
      rabbitmq:
        condition: service_healthy
      nginx:
        condition: service_healthy
      question-service:
        condition: service_healthy

  frontend:
    extends:
      file: ./../../frontend/provisioning/docker-compose.yml
      service: frontend
    depends_on:
      nginx:
        condition: service_healthy
      question-service:
        condition: service_healthy
      user-service:
        condition: service_healthy
      matching-service:
        condition: service_healthy


networks:
  shared-network:
    name: peerprep-g02
